import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import PaymentOrderLines from "./PaymentOrderLines";
import { jsonResponse } from "../../../../testUtils/authTestUtils";
const conflict = {paymentOrderId:7,recipientId:19,organizationId:3,currentSubtotal:"125.123456",proposedSubtotal:"0.000000",reason:"POSITIVE_SUBTOTAL_REQUIRED"};
test.each(["PUT", "DELETE"])("%s shows all recipient conflicts and refresh preserves a rejected edit",async method=>{
 let line={id:81,transactionId:2,organizationId:3,costDetailId:4,amount:"125.123456",memo:""};
 const error=jest.spyOn(console,"error").mockImplementation(()=>{});
 jest.spyOn(window,"confirm").mockReturnValue(true);
 const success=jest.fn();
 global.fetch=jest.fn((url,options={})=>jsonResponse(options.method?{message:"Recipient contribution required",code:"RECIPIENT_CONTRIBUTION_REQUIRED",recipientConflicts:[conflict,{...conflict,recipientId:20,currentSubtotal:"-2.000000",proposedSubtotal:"-2.000001",reason:"LEGACY_SUBTOTAL_WOULD_WORSEN"}],fieldErrors:method==="PUT"?{organizationId:"Keep a matching contribution"}:undefined}:url.includes("cost-allocations")?[{costDetailId:4,plannedAmount:"200"}]:line?[line]:[], options.method?409:200));
 render(<PaymentOrderLines paymentOrderId={7} txOptions={[{id:2,lifecycleStatus:"APPROVED"}]} orgOptions={[{id:3,name:"Original"},{id:9,name:"Proposed"}]} costDetailOptions={[{costDetailId:4,costDescription:"Equipment"}]} canManage onMutationSuccess={success}/>);
 await screen.findByLabelText("Organization for line 81");
 fireEvent.change(screen.getByLabelText("Organization for line 81"),{target:{value:"9"}});
 fireEvent.click(screen.getByTitle(method==="PUT"?"Save line":"Delete line"));
 expect(await screen.findByText(/Recipient #19/)).toBeInTheDocument();
 expect(screen.getByText(/Recipient #20/)).toBeInTheDocument();
 expect(screen.getByText(/Current subtotal: 125.123456/)).toBeInTheDocument();
 expect(screen.getByText(/nonpositive subtotal cannot/)).toBeInTheDocument();
 expect(success).not.toHaveBeenCalled();
 expect(screen.getByLabelText("Organization for line 81")).toHaveValue("9");
 line={...line,organizationId:3,amount:"126.123456"};
 fireEvent.click(screen.getByTitle("Refresh lines"));
 await waitFor(()=>expect(screen.getByLabelText("Amount for line 81").value).toBe("126.123456"));
 expect(screen.getByLabelText("Organization for line 81")).toHaveValue("9");
 expect(fetch.mock.calls.filter(([,opts])=>opts?.method)).toHaveLength(1);
 line=null;
 fireEvent.click(screen.getByTitle("Refresh lines"));
 expect(await screen.findByText(/This line is no longer available/)).toBeInTheDocument();
 expect(screen.getByLabelText("Organization for line 81")).toHaveValue("9");
 expect(screen.getByLabelText("Organization for line 81")).toBeDisabled();
 error.mockRestore();jest.restoreAllMocks();
});
