import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import ExcelJS from "exceljs";
import PaymentOrders from "./PaymentOrders";
import Recipients from "../Recipients/Recipients";
import { ProjectContext } from "../../context/ProjectContext";
jest.mock("../../context/AuthContext",()=>({useAuth:()=>({hasRole:()=>false,hasAnyRole:()=>false})}));
jest.mock("../../hooks/useMediaQuery",()=>()=>false);
jest.mock("exceljs",()=>({Workbook:jest.fn()}));
const summary = id => ({status:"CONSISTENT",source:"CURRENT_BUDGET_CONFIGURATION",currency:{id,name:"Currency"},issues:[]});
test.each([false,true])("recipient=%s exports exact amounts with separate currency totals and unavailable diagnostics",async recipient=>{
 ExcelJS.Workbook.mockImplementation(()=>{const book=new (jest.requireActual("exceljs").Workbook)();book.xlsx.writeBuffer=jest.fn().mockResolvedValue(new Uint8Array());return book;});
 URL.createObjectURL=jest.fn(()=>"blob:test");URL.revokeObjectURL=jest.fn();
 const click=jest.spyOn(HTMLAnchorElement.prototype,"click").mockImplementation(()=>{});
 const records=[{id:71,organizationId:1,paymentOrderId:71,amount:"99999999999999.999999",amountSummary:summary(1)}, {id:72,organizationId:1,paymentOrderId:72,amount:"0.000001",amountSummary:summary(2)}, {id:73,organizationId:1,paymentOrderId:73,amount:null,amountSummary:{status:"INCONSISTENT",issues:[{code:"CURRENCY_MISMATCH",lineIds:[91]}]}}];
 global.fetch=jest.fn(async url=>({ok:true,json:async()=>url.includes("/payment-order-lines/")?[{id:91,amount:"99999999999999.999999",amountCurrency:{availability:"AVAILABLE",currency:{id:1,name:"Currency"}}}]:url.includes("/payment-orders/project/")||url.includes("/recipients/by-project/")?records:[]}));
 render(<MemoryRouter><ProjectContext.Provider value={{selectedProjectId:1,projects:[{id:1,projectName:"Demo"}]}}>{recipient?<Recipients/>:<PaymentOrders/>}</ProjectContext.Provider></MemoryRouter>);
 fireEvent.click(await screen.findByRole("checkbox",{name:recipient?"Select recipient 71":"Select payment order 71"}));
 fireEvent.click(screen.getByRole("checkbox",{name:recipient?"Select recipient 72":"Select payment order 72"}));
 fireEvent.click(screen.getByRole("checkbox",{name:recipient?"Select recipient 73":"Select payment order 73"}));
 fireEvent.click(screen.getByRole("button",{name:"Export selected (3)"}));
 await waitFor(()=>expect(URL.createObjectURL).toHaveBeenCalled());
 const book=ExcelJS.Workbook.mock.results[ExcelJS.Workbook.mock.results.length-1].value;
 const sheet=book.worksheets[0];const rows=sheet.getRows(1,sheet.rowCount);const values=rows.map(row=>row.values);
 expect(JSON.stringify(values)).toContain("99999999999999.999999");
 expect(JSON.stringify(values)).toContain("CURRENCY_MISMATCH");
 expect(JSON.stringify(values)).toContain("Unavailable");
 expect(JSON.stringify(values)).not.toContain("GRAND TOTAL");
 expect(JSON.stringify(values)).not.toContain("Difference:");
 const totals=rows.filter(row=>String(row.getCell(1).value).startsWith("TOTAL"));
 const currencyTotals=recipient?totals:totals.filter(row=>String(row.getCell(1).value).startsWith("TOTAL Currency"));
 expect(currencyTotals).toHaveLength(2);
 expect(currencyTotals[0].getCell(recipient?4:5).value).toBe("99999999999999.999999");
 expect(currencyTotals[1].getCell(recipient?4:5).value).toBe(0.000001);
 click.mockRestore();
});
