import { fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import Signatures from "./Signatures";
import { ProjectContext } from "../../context/ProjectContext";
import { authValue, jsonResponse } from "../../testUtils/authTestUtils";
import { useAuth } from "../../context/AuthContext";
jest.mock("../../context/AuthContext", () => ({ useAuth: jest.fn() }));
test("compact workflow retains rejected drafts, uses existing payload, and shares filtering and selection", async () => {
  window.matchMedia = jest.fn(() => ({ matches: true, addEventListener: jest.fn(), removeEventListener: jest.fn() }));
  useAuth.mockReturnValue(authValue(["APPROVER"]));
  let fail = true;
  global.fetch = jest.fn((url, options = {}) => {
    if (options.method === "PUT") return jsonResponse(fail ? { message: "Please correct the signature", fieldErrors: { signature: "Try another value" } } : {}, fail ? 400 : 200);
    if (url.includes("/signatures/by-project/")) return jsonResponse([{ id: 7, signatureStatusId: 1, employeeId: 2, paymentOrderId: 20, signature: "Demo", signatureDate: null }]);
    if (url.includes("/payment-orders/project/")) return jsonResponse([{ id: 20, lifecycleStatus: "APPROVED" }]);
    if (url.includes("/signature-statuses/")) return jsonResponse([{ id: 1, signatureStatusName: "Booked" }]);
    if (url.includes("/employees/")) return jsonResponse([{ id: 2, firstName: "Example", lastName: "Signer" }]);
    return jsonResponse([]);
  });
  render(<ProjectContext.Provider value={{ selectedProjectId: 1, projects: [] }}><Signatures /></ProjectContext.Provider>);
  await screen.findByText("Booked");
  expect(screen.queryByRole("button", { name: "Columns" })).not.toBeInTheDocument();
  fireEvent.click(screen.getByLabelText(/Select all visible/));
  expect(screen.getByRole("button", { name: "Export selected (1)" })).toBeEnabled();
  fireEvent.click(screen.getByRole("button", { name: "Edit" }));
  const signature = screen.getByRole("textbox", { name: "Signature" });
  fireEvent.change(signature, { target: { value: "Updated demo" } }); fireEvent.blur(signature);
  expect(fetch.mock.calls.some(([, options]) => options?.method === "PUT")).toBe(false);
  fireEvent.click(screen.getByRole("button", { name: "Save" }));
  await screen.findByText("Try another value"); expect(signature).toHaveValue("Updated demo");
  expect(screen.getByRole("button", { name: "New" })).toBeDisabled();
  fail = false; fireEvent.click(screen.getByRole("button", { name: "Save" }));
  await waitFor(() => expect(screen.queryByRole("button", { name: "Save" })).not.toBeInTheDocument());
  expect(JSON.parse(fetch.mock.calls.find(([, options]) => options?.method === "PUT")[1].body)).toEqual({ signatureStatusId: 1, employeeId: 2, paymentOrderId: 20, signature: "Updated demo", signatureDate: null });
  fireEvent.click(screen.getByText(/Sort & filter/));
  fireEvent.click(screen.getByRole("button", { name: "Filter Signature" }));
  const dialog = screen.getByRole("dialog");
  fireEvent.change(within(dialog).getByRole("textbox"), { target: { value: "unmatched" } });
  fireEvent.click(within(dialog).getByRole("button", { name: "Apply" }));
  expect(await screen.findByText("No signatures match your filters.")).toBeInTheDocument();
  delete window.matchMedia;
});
